version: '3.8'

services:
  a1_assignment:
    image: a1_assignment:latest
    container_name: a1
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"  
    stdin_open: true        
    tty: true